# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0015_property_slug'),
        ('messaging', '0013_auto_20161201_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyCabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('max_count', models.PositiveSmallIntegerField()),
                ('lock_combo', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyCabinetSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reservedKey',
            fields=[
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assets.KeyCabinetSpot')),
                ('checked_in_date', models.DateField()),
                ('checked_in_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Contact')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
        migrations.AddField(
            model_name='keycabinetspot',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.KeyCabinet'),
        ),
    ]
