# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservedkey',
            old_name='checked_in_contact',
            new_name='last_used_contact',
        ),
        migrations.RenameField(
            model_name='reservedkey',
            old_name='checked_in_date',
            new_name='last_used_date',
        ),
        migrations.AddField(
            model_name='reservedkey',
            name='last_used_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservedkey',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservedkey',
            name='prop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.Property'),
        ),
        migrations.AlterField(
            model_name='reservedkey',
            name='spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.KeyCabinetSpot'),
        ),
    ]
