# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_auto_20161201_1447'),
        ('properties', '0015_property_slug'),
        ('assets', '0003_auto_20161229_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20, unique=True)),
                ('combo', models.CharField(max_length=10)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('aquired_date', models.DateField(blank=True, null=True)),
                ('combo_last_changed_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
                ('last_update_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_update_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Contact')),
                ('prop', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.Property')),
            ],
        ),
    ]
