# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('properties', '0001_initial'), ('properties', '0002_auto_20161024_2001'), ('properties', '0003_auto_20161024_2113'), ('properties', '0004_auto_20161024_2117'), ('properties', '0005_contact_message'), ('properties', '0006_auto_20161024_2155'), ('properties', '0007_auto_20161024_2155'), ('properties', '0008_auto_20161025_2136'), ('properties', '0009_auto_20161117_1303'), ('properties', '0010_auto_20161117_1509'), ('properties', '0011_property_archive_on'), ('properties', '0012_fee_lease_leasecontact_leasefee'), ('properties', '0013_auto_20161127_1402'), ('properties', '0014_auto_20161127_1453'), ('properties', '0015_auto_20161127_1531'), ('properties', '0016_auto_20161127_2029'), ('properties', '0017_auto_20161127_2102'), ('properties', '0018_auto_20161127_2103'), ('properties', '0019_auto_20161128_2144'), ('properties', '0020_auto_20161128_2324'), ('properties', '0021_auto_20161129_1148'), ('properties', '0022_auto_20161129_1220'), ('properties', '0023_auto_20161129_1227'), ('properties', '0024_auto_20161129_1302'), ('properties', '0025_auto_20161129_1634'), ('properties', '0026_auto_20161130_2049')]

    initial = True

    dependencies = [
        ('messaging', '0006_auto_20161124_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addressNumeric', models.IntegerField()),
                ('addressStreet', models.CharField(max_length=50)),
                ('addressUnit', models.CharField(blank=True, max_length=20)),
                ('addressCity', models.CharField(max_length=30)),
                ('addressState', models.CharField(max_length=20)),
                ('addressZipcode', models.CharField(max_length=10)),
                ('addressCounty', models.CharField(max_length=30)),
                ('addressFull', models.CharField(max_length=100)),
                ('addressStreet1', models.CharField(blank=True, max_length=50)),
                ('addressStreet2', models.CharField(blank=True, max_length=50)),
                ('areaHeatedSqFt', models.IntegerField(blank=True, null=True)),
                ('areaLotSqFt', models.IntegerField(blank=True, null=True)),
                ('bathroomsFull', models.IntegerField(blank=True, null=True)),
                ('bathroomsHalf', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('isMapable', models.BooleanField(default=False)),
                ('mapLatitude', models.FloatField(blank=True, null=True)),
                ('mapLongitude', models.FloatField(blank=True, null=True)),
                ('mapNotes', models.TextField(blank=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
                ('partOfTown', models.CharField(blank=True, max_length=50)),
                ('poolType', models.CharField(choices=[('none', 'none'), ('private', 'private'), ('community', 'community'), ('both', 'both')], default='none', max_length=10)),
                ('yearBuilt', models.IntegerField(blank=True, null=True)),
                ('propertyType', models.CharField(choices=[('sfhouse', 'house'), ('condo', 'condo'), ('townhouse', 'townhouse'), ('commercial', 'commercial')], default='sfhouse', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('ownerCount', models.SmallIntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('assetType', models.CharField(choices=[('appliance', 'Appliance'), ('system', 'System')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('yearAquired', models.IntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('groupMain', models.CharField(choices=[('community', 'Community'), ('included', 'Included'), ('exterior', 'Exterior'), ('interior', 'Interior')], max_length=20)),
                ('groupSub', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('companyName', models.CharField(blank=True, max_length=40)),
                ('contactName', models.CharField(blank=True, max_length=50)),
                ('phone1', models.CharField(blank=True, max_length=16)),
                ('phone2', models.CharField(blank=True, max_length=16)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('accountNumber', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='featureOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.FeatureOption'),
        ),
        migrations.AddField(
            model_name='feature',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
        migrations.AlterModelOptions(
            name='featureoption',
            options={'ordering': ('groupMain', 'groupSub', 'label')},
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('defaultAmount', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('archive_at', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('rent', 'Rent'), ('fee', 'Fee'), ('deposit', 'Deposit'), ('service', 'Service')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_dateLeaseStart', models.DateField()),
                ('terms_dateLeaseEnd', models.DateField()),
                ('terms_priceRent', models.IntegerField()),
                ('terms_depositSecurity', models.IntegerField()),
                ('terms_depositPet', models.IntegerField(blank=True, null=True)),
                ('terms_feeLate', models.IntegerField(default=100)),
                ('terms_lateGraceDays', models.IntegerField(default=3)),
                ('terms_feeLateNotice', models.IntegerField(default=25)),
                ('terms_feePet', models.IntegerField(default=0)),
                ('terms_feeCleaning', models.IntegerField()),
                ('terms_feeCarpet', models.IntegerField()),
                ('terms_feeRenewal', models.IntegerField(default=0)),
                ('start_dateLeaseSigned', models.DateField(blank=True, null=True)),
                ('start_isRenewal', models.BooleanField(default=False)),
                ('start_dateMoveIn', models.DateField(blank=True)),
                ('start_moveInNotes', models.TextField(blank=True)),
                ('end_dateMoveOut', models.DateField(blank=True)),
                ('end_actionNotes', models.TextField(blank=True)),
                ('end_moveOutNotes', models.TextField(blank=True)),
                ('end_ActionTenants', models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], max_length=30)),
                ('end_ActionTenantsDate', models.DateTimeField(blank=True, null=True)),
                ('end_ActionOwner', models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], max_length=30)),
                ('end_ActionOwnerDate', models.DateTimeField(blank=True, null=True)),
                ('end_ActionFinal', models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], max_length=30)),
                ('end_ActionFinalDate', models.DateTimeField(blank=True, null=True)),
                ('pet1', models.CharField(blank=True, max_length=30, null=True)),
                ('pet2', models.CharField(blank=True, max_length=30, null=True)),
                ('pet3', models.CharField(blank=True, max_length=30, null=True)),
                ('pet4', models.CharField(blank=True, max_length=30, null=True)),
                ('pet5', models.CharField(blank=True, max_length=30, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.Property')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tenant', 'Tenant'), ('cosigner', 'Co-signer'), ('tenant agent', "Tenant's Agent"), ('owner', 'Owner'), ('other', 'Other')], max_length=20)),
                ('isUnderage', models.BooleanField(default=False)),
                ('isFinancialyResponsible', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='messaging.Contact')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Lease')),
                ('certifiedFundsOnly', models.BooleanField(default=False)),
                ('doNotRenew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Fee')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Lease')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='marketingDescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_ActionFinal',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], default='undecided', max_length=30),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_ActionOwner',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], default='undecided', max_length=30),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_ActionTenants',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], default='undecided', max_length=30),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_actionNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_dateMoveOut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_moveOutNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_dateMoveIn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_moveInNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='archive_at',
            new_name='archived_on',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='archive_on',
            new_name='archived_at',
        ),
        migrations.AddField(
            model_name='lease',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('owner fee', 'Owner Fee'), ('tenant fee', 'Tenant Fee'), ('deposit', 'Deposit'), ('service', 'Service')], max_length=20),
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='property',
            new_name='prop',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='terms_depositPet',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='terms_depositSecurity',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='terms_feeCarpet',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='terms_feeCleaning',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='terms_feeLate',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='terms_feeLateNotice',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='terms_feePet',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='terms_feeRenewal',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='terms_dateLeaseEnd',
            new_name='dateLeaseEnd',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='terms_dateLeaseStart',
            new_name='dateLeaseStart',
        ),
        migrations.AlterField(
            model_name='property',
            name='poolType',
            field=models.CharField(choices=[('none', 'None'), ('private', 'Private'), ('community', 'Community'), ('both', 'Both')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('sfhouse', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial')], default='sfhouse', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='contactManager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='dateContractStart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='marketingDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_on', models.DateField(auto_now_add=True)),
                ('archive_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('percentageShare', models.SmallIntegerField(default=100)),
                ('holdPayments', models.BooleanField(default=False)),
                ('sendEmailNotifications', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('owner', 'Owner'), ('authorized contact', 'Contact'), ('agent', 'Sales Agent'), ('lawyer', 'Lawyer'), ('other', 'Other')], max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Contact')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='ext_MLSID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ext_appfolioID',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='petCatsOK',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='petDogsOK',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='petRestrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PropertyAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lease expiring', 'Lease Expiring'), ('moving out', 'Moving Out'), ('vacant', 'Vacant'), ('tenants needed', 'Tenants Needed'), ('active incident', 'Active Incident'), ('rent late', 'Rent Late'), ('eviction', 'Eviction'), ('upset tenant', 'Tenant Problem'), ('upset owner', 'Owner Problem'), ('info incomplete', 'Incomplete Info')], max_length=24)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('silence_on', models.DateField(blank=True, null=True)),
                ('archive_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='archived_at',
            new_name='archived_on',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='propertyalert',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
    ]
