# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20161130_2049'),
        ('properties', '0002_auto_20161201_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lease expiring', 'Lease Expiring'), ('moving out', 'Moving Out'), ('vacant', 'Vacant'), ('tenants needed', 'Tenants Needed'), ('active incident', 'Active Incident'), ('rent late', 'Rent Late'), ('eviction', 'Eviction'), ('tenant issue', 'Tenant Issue'), ('owner issue', 'Owner Issue'), ('info incomplete', 'Incomplete Info'), ('rent paid', 'Rent Paid'), ('inspection', 'Inspection'), ('service performed', 'Service Performed')], max_length=24)),
                ('priority', models.SmallIntegerField(choices=[(1, 'Urgent'), (3, 'High'), (5, 'Medium'), (9, 'Low'), (20, 'Info'), (100, 'System Log')])),
                ('modifier', models.CharField(blank=True, max_length=10, null=True)),
                ('isAlert', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('start_on', models.DateTimeField()),
                ('end_on', models.DateTimeField(blank=True, null=True)),
                ('createdByContact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Contact')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
        migrations.RemoveField(
            model_name='propertyalert',
            name='prop',
        ),
        migrations.DeleteModel(
            name='PropertyAlert',
        ),
    ]
