# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20161201_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyactivity',
            name='end_on',
        ),
        migrations.RemoveField(
            model_name='propertyactivity',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='propertyactivity',
            name='start_on',
        ),
        migrations.AddField(
            model_name='propertyactivity',
            name='activity_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyactivity',
            name='alertEnd_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyactivity',
            name='alertStart_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessdevice',
            name='ownerCount',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='defaultAmount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lease',
            name='terms_lateGraceDays',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='lease',
            name='terms_priceRent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='addressNumeric',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyactivity',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (10, 'High'), (20, 'Medium'), (30, 'Low'), (50, 'Info'), (100, 'System Log')], default=20),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='percentageShare',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
