# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20161201_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyactivity',
            name='resolved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyactivity',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Urgent'), (80, 'High'), (60, 'Normal'), (40, 'Low'), (20, 'Info'), (10, 'Log')], default=60),
        ),
        migrations.AlterField(
            model_name='propertyactivity',
            name='type',
            field=models.CharField(choices=[('lease expiring', 'Lease Expiring'), ('moving out', 'Moving Out'), ('vacant', 'Vacant'), ('tenants needed', 'Tenants Needed'), ('incident', 'Incident'), ('rent late', 'Rent Paid Late'), ('eviction', 'Eviction'), ('official notice', 'Official Notice'), ('tenant issue', 'Tenant Issue'), ('owner issue', 'Owner Issue'), ('info incomplete', 'Info Incomplete'), ('rent paid', 'Rent Paid'), ('inspection', 'Inspection'), ('service', 'Service')], max_length=24),
        ),
    ]
