# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20161202_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyactivity',
            name='type',
            field=models.CharField(choices=[('lease expiring', 'Lease Expiring'), ('lease signed', 'Lease Signed'), ('moving out', 'Moving Out'), ('vacant', 'Vacant'), ('tenants needed', 'Tenants Needed'), ('work order', 'Work Order'), ('service request', 'Service Request'), ('incident', 'Incident'), ('rent late', 'Rent Paid Late'), ('eviction', 'Eviction'), ('official notice', 'Official Notice'), ('violation', 'Violation'), ('tenant issue', 'Tenant Issue'), ('owner issue', 'Owner Issue'), ('info incomplete', 'Info Incomplete'), ('rent paid', 'Rent Paid'), ('inspection', 'Inspection'), ('service', 'Service')], max_length=24),
        ),
    ]
