# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20161202_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='terms_feeLate',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='terms_feeLateNotice',
            field=models.IntegerField(default=25),
        ),
    ]
