# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20161207_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='terms_depositSecurity',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
