# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20161221_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='addressStreet1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='addressStreet2',
        ),
        migrations.AddField(
            model_name='property',
            name='addressShort',
            field=models.CharField(default='x', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='addressState',
            field=localflavor.us.models.USStateField(default='FL', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='property',
            name='addressZipcode',
            field=localflavor.us.models.USZipCodeField(verbose_name='Zip Code'),
        ),
    ]
