# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20161221_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
