# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20161024_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='areaHeatedSqFt',
        ),
        migrations.RemoveField(
            model_name='property',
            name='areaLotSqFt',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathroomsFull',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathroomsHalf',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='isMapable',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mapLatitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mapLongitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mapNotes',
        ),
        migrations.RemoveField(
            model_name='property',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='property',
            name='partOfTown',
        ),
        migrations.RemoveField(
            model_name='property',
            name='poolType',
        ),
        migrations.RemoveField(
            model_name='property',
            name='yearBuilt',
        ),
    ]
