# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20161024_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='areaHeatedSqFt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='areaLotSqFt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroomsFull',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroomsHalf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='isMapable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='mapLatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mapLongitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mapNotes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='partOfTown',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='poolType',
            field=models.CharField(choices=[('none', 'none'), ('private', 'private'), ('community', 'community'), ('both', 'both')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='yearBuilt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
