# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bcc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='cc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='fromEmailName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
