# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20161024_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fromContact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
