# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20161025_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('ownerCount', models.SmallIntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('assetType', models.CharField(choices=[('appliance', 'Appliance'), ('system', 'System')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=20)),
                ('serial', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('yearAquired', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('groupMain', models.CharField(choices=[('community', 'Community'), ('included', 'Included'), ('exterior', 'Exterior'), ('interior', 'Interior')], max_length=20)),
                ('groupSub', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('companyName', models.CharField(blank=True, max_length=40)),
                ('contactName', models.CharField(blank=True, max_length=50)),
                ('phone1', models.CharField(blank=True, max_length=16)),
                ('phone2', models.CharField(blank=True, max_length=16)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('accountNumber', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('sfhouse', 'house'), ('condo', 'condo'), ('townhouse', 'townhouse'), ('commercial', 'commercial')], default='sfhouse', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
        migrations.AddField(
            model_name='feature',
            name='featureOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.FeatureOption'),
        ),
        migrations.AddField(
            model_name='feature',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
        migrations.AddField(
            model_name='asset',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
    ]
