# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20161117_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureoption',
            options={'ordering': ('groupMain', 'groupSub', 'label')},
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
