# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20161124_1447'),
        ('properties', '0011_property_archive_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('defaultAmount', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('archive_at', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('rent', 'Rent'), ('fee', 'Fee'), ('deposit', 'Deposit'), ('service', 'Service')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_dateLeaseStart', models.DateField()),
                ('terms_dateLeaseEnd', models.DateField()),
                ('terms_priceRent', models.IntegerField()),
                ('terms_depositSecurity', models.IntegerField()),
                ('terms_depositPet', models.IntegerField(blank=True, null=True)),
                ('terms_feeLate', models.IntegerField(default=100)),
                ('terms_lateGraceDays', models.IntegerField(default=3)),
                ('terms_feeLateNotice', models.IntegerField(default=25)),
                ('terms_feePet', models.IntegerField(default=0)),
                ('terms_feeCleaning', models.IntegerField()),
                ('terms_feeCarpet', models.IntegerField()),
                ('terms_feeRenewal', models.IntegerField(default=0)),
                ('start_dateLeaseSigned', models.DateField(blank=True, null=True)),
                ('start_isRenewal', models.BooleanField(default=False)),
                ('start_dateMoveIn', models.DateField(blank=True)),
                ('start_moveInNotes', models.TextField(blank=True)),
                ('end_dateMoveOut', models.DateField(blank=True)),
                ('end_actionNotes', models.TextField(blank=True)),
                ('end_moveOutNotes', models.TextField(blank=True)),
                ('end_ActionTenants', models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], max_length=30)),
                ('end_ActionTenantsDate', models.DateTimeField(blank=True, null=True)),
                ('end_ActionOwner', models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], max_length=30)),
                ('end_ActionOwnerDate', models.DateTimeField(blank=True, null=True)),
                ('end_ActionFinal', models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], max_length=30)),
                ('end_ActionFinalDate', models.DateTimeField(blank=True, null=True)),
                ('pet1', models.CharField(blank=True, max_length=30, null=True)),
                ('pet2', models.CharField(blank=True, max_length=30, null=True)),
                ('pet3', models.CharField(blank=True, max_length=30, null=True)),
                ('pet4', models.CharField(blank=True, max_length=30, null=True)),
                ('pet5', models.CharField(blank=True, max_length=30, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.Property')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tenant', 'Tenant'), ('cosigner', 'Co-signer'), ('owner', 'Owner'), ('owner agent', "Owner's Agent"), ('owner lawyer', "Owner's Lawyer"), ('other', 'Other')], max_length=20)),
                ('isUnderage', models.BooleanField(default=False)),
                ('isFinancialyResponsible', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='messaging.Contact')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Lease')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Fee')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Lease')),
            ],
        ),
    ]
