# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20161127_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='end_ActionFinal',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], default='undecided', max_length=30),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_ActionOwner',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], default='undecided', max_length=30),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_ActionTenants',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('new tenant', 'Find New Tenant'), ('current tenant', 'Keep Current Tenant'), ('return to owner', 'Return to Owner'), ('for sale', 'List for Sale'), ('month to month', 'Month to Month')], default='undecided', max_length=30),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_actionNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_dateMoveOut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_moveOutNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_dateMoveIn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_moveInNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
