# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_auto_20161127_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('owner fee', 'Owner Fee'), ('tenant fee', 'Tenant Fee'), ('deposit', 'Deposit'), ('service', 'Service')], max_length=20),
        ),
    ]
