# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_auto_20161127_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='terms_dateLeaseEnd',
            new_name='dateLeaseEnd',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='terms_dateLeaseStart',
            new_name='dateLeaseStart',
        ),
        migrations.AlterField(
            model_name='property',
            name='poolType',
            field=models.CharField(choices=[('none', 'None'), ('private', 'Private'), ('community', 'Community'), ('both', 'Both')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('sfhouse', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial')], default='sfhouse', max_length=20),
        ),
    ]
