# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20161128_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='dateContractStart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='marketingDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
