# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20161124_1447'),
        ('properties', '0021_auto_20161129_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_at', models.DateField(auto_now_add=True)),
                ('archive_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('percentageShare', models.SmallIntegerField(default=100)),
                ('taxPayerName', models.CharField(max_length=50)),
                ('taxPayerID', models.CharField(max_length=12)),
                ('holdPayments', models.BooleanField(default=False)),
                ('sendEmailNotifications', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('owner', 'Owner'), ('primary', 'Primary Contact'), ('agent', 'Sales Agent'), ('lawyer', 'Lawyer'), ('other', 'Other')], max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='messaging.Contact')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
        migrations.AddField(
            model_name='leasecontact',
            name='certifiedFundsOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leasecontact',
            name='doNotRenew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leasecontact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontact',
            name='type',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('cosigner', 'Co-signer'), ('tenant agent', "Tenant's Agent"), ('owner', 'Owner'), ('other', 'Other')], max_length=20),
        ),
    ]
