# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20161129_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyowner',
            name='taxPayerID',
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='taxPayerName',
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='type',
            field=models.CharField(choices=[('owner', 'Owner'), ('Authorized Contact', 'Authorized Contact'), ('agent', 'Sales Agent'), ('lawyer', 'Lawyer'), ('other', 'Other')], max_length=20),
        ),
    ]
