# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_auto_20161129_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ext_MLSID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ext_appfolioID',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='petCatsOK',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='petDogsOK',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='petRestrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='type',
            field=models.CharField(choices=[('owner', 'Owner'), ('Authorized Contact', 'Contact'), ('agent', 'Sales Agent'), ('lawyer', 'Lawyer'), ('other', 'Other')], max_length=20),
        ),
    ]
