# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_auto_20161129_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyowner',
            name='type',
            field=models.CharField(choices=[('owner', 'Owner'), ('authorized contact', 'Contact'), ('agent', 'Sales Agent'), ('lawyer', 'Lawyer'), ('other', 'Other')], max_length=20),
        ),
    ]
