# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_auto_20161129_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lease expiring', 'Lease Expiring'), ('moving out', 'Moving Out'), ('vacant', 'Vacant'), ('tenants needed', 'Tenants Needed'), ('active incident', 'Active Incident'), ('rent late', 'Rent Late'), ('eviction', 'Eviction'), ('upset tenant', 'Tenant Problem'), ('upset owner', 'Owner Problem'), ('info incomplete', 'Incomplete Info')], max_length=24)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('silence_on', models.DateField(blank=True, null=True)),
                ('archive_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='archived_at',
            new_name='archived_on',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='archived_at',
            new_name='archived_on',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='propertyowner',
            old_name='active_at',
            new_name='active_on',
        ),
        migrations.RenameField(
            model_name='propertyowner',
            old_name='archive_at',
            new_name='archive_on',
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Contact'),
        ),
        migrations.AddField(
            model_name='propertyalert',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
    ]
