# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFirst', models.CharField(max_length=30)),
                ('nameLast', models.CharField(max_length=30)),
                ('nameMiddle', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromEmail', models.CharField(max_length=254)),
                ('fromEmailName', models.CharField(blank=True, max_length=100)),
                ('fromContact', models.IntegerField(blank=True, null=True)),
                ('cc', models.CharField(blank=True, max_length=1000)),
                ('bcc', models.CharField(blank=True, max_length=1000)),
                ('subject', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('propertyID', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesterContactID', models.IntegerField()),
                ('threadType', models.CharField(max_length=20)),
                ('propertyID', models.IntegerField()),
                ('assignedToContactID', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
