# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20161102_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='toContact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='toEmail',
            field=models.CharField(default='steve@kumbarealty.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='toEmailName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
