# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20161116_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
    ]
