# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20161124_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='taxPayerID',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='taxPayerName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
