# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20161130_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('x', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='isTenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, choices=[('', ''), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Mx', 'Mx')], max_length=6, null=True),
        ),
    ]
