# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_auto_20161201_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fromContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesages_from', to='messaging.Contact'),
        ),
        migrations.AlterField(
            model_name='message',
            name='toContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesages_to', to='messaging.Contact'),
        ),
    ]
